apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing-config
  namespace: default
spec:
  tracing:
    samplingRate: "1"
    stdout: true
    otel:
      endpointAddress: "otel-gateway-collector.astroshop.svc.cluster.local:4317"
      isSecure: false
      protocol: grpc 
