apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "12"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1","meta.helm.sh/release-name":"astroshop","meta.helm.sh/release-namespace":"staging-astroshop"},"generation":1,"labels":{"app.kubernetes.io/component":"frontendproxy","app.kubernetes.io/instance":"astroshop","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"astroshop-frontendproxy","app.kubernetes.io/part-of":"opentelemetry-demo","app.kubernetes.io/version":"1.11.1","helm.sh/chart":"opentelemetry-demo-0.32.8","opentelemetry.io/name":"astroshop-frontendproxy"},"name":"astroshop-frontendproxy","namespace":"staging-astroshop"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"opentelemetry.io/name":"astroshop-frontendproxy"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"dt.owner":"dev-team-ux"},"labels":{"app.kubernetes.io/component":"frontendproxy","app.kubernetes.io/instance":"astroshop","app.kubernetes.io/name":"astroshop-frontendproxy","opentelemetry.io/name":"astroshop-frontendproxy"}},"spec":{"containers":[{"env":[{"name":"OTEL_SERVICE_NAME","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.labels['app.kubernetes.io/component']"}}},{"name":"OTEL_COLLECTOR_NAME","value":"dynatrace-otel-gateway-collector"},{"name":"ENVOY_PORT","value":"8080"},{"name":"FLAGD_HOST","value":"astroshop-flagd"},{"name":"FLAGD_PORT","value":"8013"},{"name":"FRONTEND_HOST","value":"astroshop-frontend"},{"name":"FRONTEND_PORT","value":"8080"},{"name":"GRAFANA_SERVICE_HOST","value":"astroshop-grafana"},{"name":"GRAFANA_SERVICE_PORT","value":"80"},{"name":"IMAGE_PROVIDER_HOST","value":"astroshop-imageprovider"},{"name":"IMAGE_PROVIDER_PORT","value":"8081"},{"name":"JAEGER_SERVICE_HOST","value":"astroshop-jaeger-query"},{"name":"JAEGER_SERVICE_PORT","value":"16686"},{"name":"LOCUST_WEB_HOST","value":"astroshop-loadgenerator"},{"name":"LOCUST_WEB_PORT","value":"8089"},{"name":"OTEL_COLLECTOR_HOST","value":"$(OTEL_COLLECTOR_NAME)"},{"name":"OTEL_COLLECTOR_PORT_GRPC","value":"4317"},{"name":"OTEL_COLLECTOR_PORT_HTTP","value":"4318"}],"image":"ghcr.io/open-telemetry/demo:1.12.0-frontendproxy","imagePullPolicy":"Always","name":"frontendproxy","ports":[{"containerPort":8080,"name":"service","protocol":"TCP"}],"resources":{"limits":{"memory":"50Mi"}},"securityContext":{"runAsGroup":101,"runAsNonRoot":true,"runAsUser":101},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"serviceAccount":"astroshop","serviceAccountName":"astroshop","terminationGracePeriodSeconds":30}}}}
    meta.helm.sh/release-name: astroshop
    meta.helm.sh/release-namespace: staging-astroshop
  creationTimestamp: "2024-12-04T17:41:59Z"
  generation: 14
  labels:
    app.kubernetes.io/component: frontendproxy
    app.kubernetes.io/instance: astroshop
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: astroshop-frontendproxy
    app.kubernetes.io/part-of: opentelemetry-demo
    app.kubernetes.io/version: 1.11.1
    helm.sh/chart: opentelemetry-demo-0.32.8
    opentelemetry.io/name: astroshop-frontendproxy
  name: astroshop-frontendproxy
  namespace: staging-astroshop
  resourceVersion: "317992520"
  uid: f101530b-ba4d-4f98-b579-075d8fbe64d9
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      opentelemetry.io/name: astroshop-frontendproxy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        dt.owner: dev-team-ux
        kubectl.kubernetes.io/restartedAt: "2024-12-10T20:10:44Z"
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: frontendproxy
        app.kubernetes.io/instance: astroshop
        app.kubernetes.io/name: astroshop-frontendproxy
        opentelemetry.io/name: astroshop-frontendproxy
    spec:
      containers:
      - env:
        - name: OTEL_SERVICE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['app.kubernetes.io/component']
        - name: OTEL_COLLECTOR_NAME
          value: dynatrace-otel-gateway-collector
        - name: ENVOY_PORT
          value: "8080"
        - name: FLAGD_HOST
          value: astroshop-flagd
        - name: FLAGD_PORT
          value: "8013"
        - name: FRONTEND_HOST
          value: astroshop-frontend
        - name: FRONTEND_PORT
          value: "8080"
        - name: GRAFANA_SERVICE_HOST
          value: astroshop-grafana
        - name: GRAFANA_SERVICE_PORT
          value: "80"
        - name: IMAGE_PROVIDER_HOST
          value: astroshop-imageprovider
        - name: IMAGE_PROVIDER_PORT
          value: "8081"
        - name: JAEGER_SERVICE_HOST
          value: astroshop-jaeger-query
        - name: JAEGER_SERVICE_PORT
          value: "16686"
        - name: LOCUST_WEB_HOST
          value: astroshop-loadgenerator
        - name: LOCUST_WEB_PORT
          value: "8089"
        - name: OTEL_COLLECTOR_HOST
          value: $(OTEL_COLLECTOR_NAME)
        - name: OTEL_COLLECTOR_PORT_GRPC
          value: "4317"
        - name: OTEL_COLLECTOR_PORT_HTTP
          value: "4318"
        image: ghcr.io/open-telemetry/demo:1.12.0-frontendproxy
        imagePullPolicy: Always
        name: frontendproxy
        ports:
        - containerPort: 8080
          name: service
          protocol: TCP
        resources:
          limits:
            memory: 50Mi
        securityContext:
          runAsGroup: 101
          runAsNonRoot: true
          runAsUser: 101
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: astroshop
      serviceAccountName: astroshop
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2024-12-04T17:42:00Z"
    lastUpdateTime: "2024-12-16T11:15:59Z"
    message: ReplicaSet "astroshop-frontendproxy-56748d6c78" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-12-16T11:16:00Z"
    lastUpdateTime: "2024-12-16T11:16:00Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 14
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
