apiVersion: v1
kind: PersistentVolume
metadata:
  name: product-catalog-storage
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  gcePersistentDisk:
    pdName: example-disk
    fsType: ext4