apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: product-catalog-storage
  namespace: staging-astroshop
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard