ingressHostUrl: "astro.whydevslovedynatrace.com"
#ingressWhitelistSourceRange: 10.224.0.0/12,195.50.84.64/27,83.164.160.102/32,83.164.153.224/28,80.80.253.56/32,213.143.108.80/29,157.25.19.96/27,82.177.196.146/32,144.121.39.106/32,50.221.151.250/32,50.247.212.21/32,50.219.104.42/32,71.24.151.161/32,12.188.200.30/32,64.85.148.114/32,216.176.22.146/32,50.219.104.50/32,50.76.51.61/32
#prodCatalogPvcStorageClass: local-path
collector_tenant_endpoint: donotstore
collector_tenant_token: donotstore
#lambda_url: "https://lambdaurl.execute-api.us-east-1.amazonaws.com/Stg"

opentelemetry-demo:
  components:
    loadgenerator:
      envOverrides:
        - name: LOCUST_HOST
          value: http://astro.whydevslovedynatrace.com
    frontend:
      envOverrides:
      - name: DT_LOGLEVELCON # https://www.dynatrace.com/support/help/shortlink/agent-logging
        value: "" # info
      - name: DT_LOGCON_PROC
        value: "" # stdout
      - name: DT_LOGGING_DESTINATION
        value: "" # stdout 
      - name: DT_LOGGING_NODEJS_FLAGS
        value: ''  # Exporter=true,SpanProcessor=true,Propagator=true,Core=true
      - name: OTEL_TRACES_EXPORTER
        value: 'none' # 'console', 'none', 'otlp'
      - name: OTEL_LOGS_EXPORTER
        value: 'none' # 'console', 'none', 'otlp'
      - name: OTEL_METRICS_EXPORTER
        value: 'console,otlp' # 'console', 'none', 'otlp'
      - name: OTEL_NODE_DISABLED_INSTRUMENTATIONS # https://github.com/open-telemetry/opentelemetry-js-contrib/blob/167dced09de0d2104561542b4f83047fa656505f/metapackages/auto-instrumentations-node/package.json#L51
        value: ''   # other examples - http,grpc,dns,net
      - name: NODE_OPTIONS
        value: '' # - do not instrument at all with things like '-r ./Instrumentation.js' Avoid duplicate spans from OA and Otel - https://opentelemetry.io/docs/zero-code/js/
      - name: PUBLIC_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT # This is used on the client-side for sending traces to the backend
        value: ''
      - name: NEXT_OTEL_VERBOSE
        value: '0'
      - name: ENV_PLATFORM
        value: 'DEV'