apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    meta.helm.sh/release-name: astroshop
    meta.helm.sh/release-namespace: astroshop
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  labels:
    app.kubernetes.io/component: frontendproxy
    app.kubernetes.io/instance: astroshop
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: astroshop-frontendproxy
    app.kubernetes.io/part-of: opentelemetry-demo
    app.kubernetes.io/version: 1.12.0
    helm.sh/chart: opentelemetry-demo-0.33.5
    opentelemetry.io/name: astroshop-frontendproxy
  name: astroshop-frontendproxy
  namespace: astroshop
spec:
  ingressClassName: nginx
  rules:
  - host: astro.whydevslovedynatrace.com
    http:
      paths:
      - backend:
          service:
            name: astroshop-frontendproxy
            port:
              number: 8080
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - astrosho.whydevslovedynatrace.com
    secretName: wdldt-astro-tls
