apiVersion: v1
kind: Secret
metadata:
  name: dynatrace-otelcol-dt-api-credentials
type: Opaque
data:
  DT_ENDPOINT: {{ .Values.collector_tenant_endpoint | b64enc }}
  DT_API_TOKEN: {{ .Values.collector_tenant_token | b64enc }}